-- English names for the catalogue: what an English-speaking owner reads instead of the
-- Russian trade name. Compiled 2026-10-07 for every row of catalog-v1.sql and catalog-v2.sql
-- whose name is not already Latin (MaxiDrops is, and keeps name_en null).
--
-- Mostly the product's own Latin name from its aliases (Нобивак Tricat Trio → Nobivac
-- Tricat Trio). Where that alias dropped what tells two rows apart — «капли», «ошейник»,
-- the letter of Гельминтал К/С/Т — the English name says it again, transliterating
-- domestic brands that have no Latin name of their own (Chistotel, not «Celandine»).
--
-- Run after migration 20261007120000_health_products_name_en.sql, and after catalog-v1/v2.
-- Safe to run more than once: each row is an update by (kind, lower(name)).

begin;

update public.health_products set name_en = 'ARRIAH-Rabivak' where kind = 'vaccine' and lower(name) = lower('АРРИАХ-Рабивак');
update public.health_products set name_en = 'Asterion DHPPiL' where kind = 'vaccine' and lower(name) = lower('Астерион DHPPiL');
update public.health_products set name_en = 'Asterion DHPPiLR' where kind = 'vaccine' and lower(name) = lower('Астерион DHPPiLR');
update public.health_products set name_en = 'Biovac DPAL' where kind = 'vaccine' and lower(name) = lower('Биовак-DPAL');
update public.health_products set name_en = 'Biocan DHPPi+L' where kind = 'vaccine' and lower(name) = lower('Биокан DHPPi+L');
update public.health_products set name_en = 'Biocan DHPPi+LR' where kind = 'vaccine' and lower(name) = lower('Биокан DHPPi+LR');
update public.health_products set name_en = 'Biocan LR' where kind = 'vaccine' and lower(name) = lower('Биокан LR');
update public.health_products set name_en = 'Biocan Puppy' where kind = 'vaccine' and lower(name) = lower('Биокан Puppy');
update public.health_products set name_en = 'Biocan R' where kind = 'vaccine' and lower(name) = lower('Биокан R');
update public.health_products set name_en = 'Biocan Novel DHPPi/L4R' where kind = 'vaccine' and lower(name) = lower('Биокан Новел DHPPi/L4R');
update public.health_products set name_en = 'Biofel PCH' where kind = 'vaccine' and lower(name) = lower('Биофел PCH');
update public.health_products set name_en = 'Biofel PCHR' where kind = 'vaccine' and lower(name) = lower('Биофел PCHR');
update public.health_products set name_en = 'Vanguard 7' where kind = 'vaccine' and lower(name) = lower('Вангард 7');
update public.health_products set name_en = 'Vanguard Plus 5 L4 CV' where kind = 'vaccine' and lower(name) = lower('Вангард Плюс 5 L4 CV');
update public.health_products set name_en = 'Hexakanivac' where kind = 'vaccine' and lower(name) = lower('Гексаканивак');
update public.health_products set name_en = 'Defensor 3' where kind = 'vaccine' and lower(name) = lower('Дефенсор 3');
update public.health_products set name_en = 'Dipentavac' where kind = 'vaccine' and lower(name) = lower('Дипентавак');
update public.health_products set name_en = 'Duramune Max 5-CvK/4L' where kind = 'vaccine' and lower(name) = lower('Дюрамун Макс 5-CvK/4L');
update public.health_products set name_en = 'Duramune Max 5/4L' where kind = 'vaccine' and lower(name) = lower('Дюрамун Макс 5/4L');
update public.health_products set name_en = 'Canigen DHA2PPi/L' where kind = 'vaccine' and lower(name) = lower('Каниген DHA2PPi/L');
update public.health_products set name_en = 'Canigen DHA2PPi/LR' where kind = 'vaccine' and lower(name) = lower('Каниген DHA2PPi/LR');
update public.health_products set name_en = 'Karnikan Puppy DP' where kind = 'vaccine' and lower(name) = lower('Карникан Puppy DP');
update public.health_products set name_en = 'Karnikan-4' where kind = 'vaccine' and lower(name) = lower('Карникан-4');
update public.health_products set name_en = 'Karnikan-5R' where kind = 'vaccine' and lower(name) = lower('Карникан-5R');
update public.health_products set name_en = 'Karnifel PCH' where kind = 'vaccine' and lower(name) = lower('Карнифел PCH');
update public.health_products set name_en = 'Karnifel PCHR' where kind = 'vaccine' and lower(name) = lower('Карнифел PCHR');
update public.health_products set name_en = 'Quadricat' where kind = 'vaccine' and lower(name) = lower('Квадрикат');
update public.health_products set name_en = 'Leukocell 2' where kind = 'vaccine' and lower(name) = lower('Лейкоцел 2');
update public.health_products set name_en = 'Leominor' where kind = 'vaccine' and lower(name) = lower('Леоминор');
update public.health_products set name_en = 'Multikan-4' where kind = 'vaccine' and lower(name) = lower('Мультикан-4');
update public.health_products set name_en = 'Multikan-6' where kind = 'vaccine' and lower(name) = lower('Мультикан-6');
update public.health_products set name_en = 'Multikan-8' where kind = 'vaccine' and lower(name) = lower('Мультикан-8');
update public.health_products set name_en = 'Multifel' where kind = 'vaccine' and lower(name) = lower('Мультифел');
update public.health_products set name_en = 'Nobivac DHP' where kind = 'vaccine' and lower(name) = lower('Нобивак DHP');
update public.health_products set name_en = 'Nobivac DHPPi' where kind = 'vaccine' and lower(name) = lower('Нобивак DHPPi');
update public.health_products set name_en = 'Nobivac Ducat' where kind = 'vaccine' and lower(name) = lower('Нобивак Ducat');
update public.health_products set name_en = 'Nobivac KC' where kind = 'vaccine' and lower(name) = lower('Нобивак KC');
update public.health_products set name_en = 'Nobivac L4' where kind = 'vaccine' and lower(name) = lower('Нобивак L4');
update public.health_products set name_en = 'Nobivac Lepto' where kind = 'vaccine' and lower(name) = lower('Нобивак Lepto');
update public.health_products set name_en = 'Nobivac Puppy DP' where kind = 'vaccine' and lower(name) = lower('Нобивак Puppy DP');
update public.health_products set name_en = 'Nobivac Rabies' where kind = 'vaccine' and lower(name) = lower('Нобивак Rabies');
update public.health_products set name_en = 'Nobivac RL' where kind = 'vaccine' and lower(name) = lower('Нобивак RL');
update public.health_products set name_en = 'Nobivac Tricat Trio' where kind = 'vaccine' and lower(name) = lower('Нобивак Tricat Trio');
update public.health_products set name_en = 'Purevax FeLV' where kind = 'vaccine' and lower(name) = lower('Пуревакс FeLV');
update public.health_products set name_en = 'Purevax RCP' where kind = 'vaccine' and lower(name) = lower('Пуревакс RCP');
update public.health_products set name_en = 'Purevax RCP Rabies' where kind = 'vaccine' and lower(name) = lower('Пуревакс RCP Rabies');
update public.health_products set name_en = 'Purevax RCPCh' where kind = 'vaccine' and lower(name) = lower('Пуревакс RCPCh');
update public.health_products set name_en = 'Purevax RCPCh Rabies' where kind = 'vaccine' and lower(name) = lower('Пуревакс RCPCh Rabies');
update public.health_products set name_en = 'Rabigen Mono' where kind = 'vaccine' and lower(name) = lower('Рабиген Моно');
update public.health_products set name_en = 'Rabisin' where kind = 'vaccine' and lower(name) = lower('Рабизин');
update public.health_products set name_en = 'Rabikan' where kind = 'vaccine' and lower(name) = lower('Рабикан');
update public.health_products set name_en = 'Rabiks' where kind = 'vaccine' and lower(name) = lower('Рабикс');
update public.health_products set name_en = 'Rabifel' where kind = 'vaccine' and lower(name) = lower('Рабифел');
update public.health_products set name_en = 'Feligen CRP' where kind = 'vaccine' and lower(name) = lower('Фелиген CRP');
update public.health_products set name_en = 'Feligen CRP/R' where kind = 'vaccine' and lower(name) = lower('Фелиген CRP/R');
update public.health_products set name_en = 'Felocell 4' where kind = 'vaccine' and lower(name) = lower('Фелоцел 4');
update public.health_products set name_en = 'Felocell CVR' where kind = 'vaccine' and lower(name) = lower('Фелоцел CVR');
update public.health_products set name_en = 'Eurican DHPPi2-L' where kind = 'vaccine' and lower(name) = lower('Эурикан DHPPI2-L');
update public.health_products set name_en = 'Eurican DHPPi2-LR' where kind = 'vaccine' and lower(name) = lower('Эурикан DHPPI2-LR');
update public.health_products set name_en = 'Eurican Primo' where kind = 'vaccine' and lower(name) = lower('Эурикан Primo');
update public.health_products set name_en = 'Advantage' where kind = 'antiparasitic' and lower(name) = lower('Адвантейдж');
update public.health_products set name_en = 'Advantix' where kind = 'antiparasitic' and lower(name) = lower('Адвантикс');
update public.health_products set name_en = 'Advocate' where kind = 'antiparasitic' and lower(name) = lower('Адвокат');
update public.health_products set name_en = 'Azinox' where kind = 'antiparasitic' and lower(name) = lower('Азинокс');
update public.health_products set name_en = 'Azinox Plus' where kind = 'antiparasitic' and lower(name) = lower('Азинокс Плюс');
update public.health_products set name_en = 'Akaromectin' where kind = 'antiparasitic' and lower(name) = lower('Акаромектин');
update public.health_products set name_en = 'Alben S' where kind = 'antiparasitic' and lower(name) = lower('Альбен С');
update public.health_products set name_en = 'Amitrazin' where kind = 'antiparasitic' and lower(name) = lower('Амитразин');
update public.health_products set name_en = 'Ataxxa' where kind = 'antiparasitic' and lower(name) = lower('Атакса');
update public.health_products set name_en = 'Bars drops' where kind = 'antiparasitic' and lower(name) = lower('Барс капли');
update public.health_products set name_en = 'Bars ear drops' where kind = 'antiparasitic' and lower(name) = lower('Барс капли ушные');
update public.health_products set name_en = 'Bars collar' where kind = 'antiparasitic' and lower(name) = lower('Барс ошейник');
update public.health_products set name_en = 'Bars Spot-on' where kind = 'antiparasitic' and lower(name) = lower('Барс Спот-он');
update public.health_products set name_en = 'Bars spray' where kind = 'antiparasitic' and lower(name) = lower('Барс спрей');
update public.health_products set name_en = 'Bars Forte' where kind = 'antiparasitic' and lower(name) = lower('Барс Форте');
update public.health_products set name_en = 'Bars Forte spray' where kind = 'antiparasitic' and lower(name) = lower('Барс Форте спрей');
update public.health_products set name_en = 'Beaphar collar' where kind = 'antiparasitic' and lower(name) = lower('Беафар ошейник');
update public.health_products set name_en = 'Bimaxgard Tabs' where kind = 'antiparasitic' and lower(name) = lower('Бимаксгард ТАБС');
update public.health_products set name_en = 'BlohNet max' where kind = 'antiparasitic' and lower(name) = lower('БлохНэт max');
update public.health_products set name_en = 'Bolfo collar' where kind = 'antiparasitic' and lower(name) = lower('Больфо ошейник');
update public.health_products set name_en = 'Bravecto' where kind = 'antiparasitic' and lower(name) = lower('Бравекто');
update public.health_products set name_en = 'Bravecto Plus' where kind = 'antiparasitic' and lower(name) = lower('Бравекто Плюс');
update public.health_products set name_en = 'Bravecto Spot-on' where kind = 'antiparasitic' and lower(name) = lower('Бравекто Спот Он');
update public.health_products set name_en = 'Broadline' where kind = 'antiparasitic' and lower(name) = lower('Бродлайн');
update public.health_products set name_en = 'Vectra 3D' where kind = 'antiparasitic' and lower(name) = lower('Вектра 3D');
update public.health_products set name_en = 'Vectra Felis' where kind = 'antiparasitic' and lower(name) = lower('Вектра Фелис');
update public.health_products set name_en = 'Vepripak' where kind = 'antiparasitic' and lower(name) = lower('Веприпак');
update public.health_products set name_en = 'Vetlaner' where kind = 'antiparasitic' and lower(name) = lower('Ветланер');
update public.health_products set name_en = 'Gelmimax' where kind = 'antiparasitic' and lower(name) = lower('Гельмимакс');
update public.health_products set name_en = 'Gelmintal K' where kind = 'antiparasitic' and lower(name) = lower('Гельминтал К');
update public.health_products set name_en = 'Gelmintal S' where kind = 'antiparasitic' and lower(name) = lower('Гельминтал С');
update public.health_products set name_en = 'Gelmintal syrup' where kind = 'antiparasitic' and lower(name) = lower('Гельминтал сироп');
update public.health_products set name_en = 'Gelmintal T' where kind = 'antiparasitic' and lower(name) = lower('Гельминтал Т');
update public.health_products set name_en = 'Dana Spot-on' where kind = 'antiparasitic' and lower(name) = lower('Дана Спот-он');
update public.health_products set name_en = 'Dana Ultra drops' where kind = 'antiparasitic' and lower(name) = lower('Дана Ультра капли');
update public.health_products set name_en = 'Dana Ultra collar' where kind = 'antiparasitic' and lower(name) = lower('Дана Ультра ошейник');
update public.health_products set name_en = 'Dana Ultra spray' where kind = 'antiparasitic' and lower(name) = lower('Дана Ультра спрей');
update public.health_products set name_en = 'Dekta Forte' where kind = 'antiparasitic' and lower(name) = lower('Декта Форте');
update public.health_products set name_en = 'Dehinel' where kind = 'antiparasitic' and lower(name) = lower('Дехинел');
update public.health_products set name_en = 'Dehinel Plus' where kind = 'antiparasitic' and lower(name) = lower('Дехинел Плюс');
update public.health_products set name_en = 'Dironet' where kind = 'antiparasitic' and lower(name) = lower('Диронет');
update public.health_products set name_en = 'Dironet Junior' where kind = 'antiparasitic' and lower(name) = lower('Диронет Джуниор');
update public.health_products set name_en = 'Dironet Spot-on' where kind = 'antiparasitic' and lower(name) = lower('Диронет Спот-он');
update public.health_products set name_en = 'Dironet suspension' where kind = 'antiparasitic' and lower(name) = lower('Диронет суспензия');
update public.health_products set name_en = 'Dirofen' where kind = 'antiparasitic' and lower(name) = lower('Дирофен');
update public.health_products set name_en = 'Dirofen Max' where kind = 'antiparasitic' and lower(name) = lower('Дирофен Макс');
update public.health_products set name_en = 'Doctor Zoo collar' where kind = 'antiparasitic' and lower(name) = lower('Доктор ZOO ошейник');
update public.health_products set name_en = 'Drontal' where kind = 'antiparasitic' and lower(name) = lower('Дронтал');
update public.health_products set name_en = 'Drontal Plus' where kind = 'antiparasitic' and lower(name) = lower('Дронтал плюс');
update public.health_products set name_en = 'Ivermek spray' where kind = 'antiparasitic' and lower(name) = lower('Ивермек-спрей');
update public.health_products set name_en = 'Insectal drops' where kind = 'antiparasitic' and lower(name) = lower('Инсектал капли');
update public.health_products set name_en = 'Insectal Combo' where kind = 'antiparasitic' and lower(name) = lower('Инсектал Комбо');
update public.health_products set name_en = 'Insectal collar' where kind = 'antiparasitic' and lower(name) = lower('Инсектал ошейник');
update public.health_products set name_en = 'Inspector Quadro' where kind = 'antiparasitic' and lower(name) = lower('Инспектор Квадро');
update public.health_products set name_en = 'Inspector Quadro Tabs' where kind = 'antiparasitic' and lower(name) = lower('Инспектор Квадро Табс');
update public.health_products set name_en = 'Inspector Mini' where kind = 'antiparasitic' and lower(name) = lower('Инспектор Мини');
update public.health_products set name_en = 'Inspector spray' where kind = 'antiparasitic' and lower(name) = lower('Инспектор спрей');
update public.health_products set name_en = 'Inspector Total' where kind = 'antiparasitic' and lower(name) = lower('Инспектор Тотал');
update public.health_products set name_en = 'Caniquantel Plus' where kind = 'antiparasitic' and lower(name) = lower('Каниквантел Плюс');
update public.health_products set name_en = 'Kvantum' where kind = 'antiparasitic' and lower(name) = lower('Квантум');
update public.health_products set name_en = 'Kiltix' where kind = 'antiparasitic' and lower(name) = lower('Килтикс');
update public.health_products set name_en = 'Milprazon' where kind = 'antiparasitic' and lower(name) = lower('Милпразон');
update public.health_products set name_en = 'Milbemax' where kind = 'antiparasitic' and lower(name) = lower('Мильбемакс');
update public.health_products set name_en = 'Milbecin Neo' where kind = 'antiparasitic' and lower(name) = lower('Мильбецин Нео');
update public.health_products set name_en = 'Milmax-Nita' where kind = 'antiparasitic' and lower(name) = lower('Мильмакс-Нита');
update public.health_products set name_en = 'NexGard Spectra' where kind = 'antiparasitic' and lower(name) = lower('НексгарД Спектра');
update public.health_products set name_en = 'Neoterica Protecto drops' where kind = 'antiparasitic' and lower(name) = lower('Неотерика Протекто капли');
update public.health_products set name_en = 'Neoterica Protecto collar' where kind = 'antiparasitic' and lower(name) = lower('Неотерика Протекто ошейник');
update public.health_products set name_en = 'Okvet ExpressTabs' where kind = 'antiparasitic' and lower(name) = lower('Оквет ЭкспрессТабс');
update public.health_products set name_en = 'Otodectin' where kind = 'antiparasitic' and lower(name) = lower('Отодектин');
update public.health_products set name_en = 'Otoferonol Gold' where kind = 'antiparasitic' and lower(name) = lower('Отоферонол Голд');
update public.health_products set name_en = 'Pinpramil' where kind = 'antiparasitic' and lower(name) = lower('Пинпрамиль');
update public.health_products set name_en = 'Poliverkan' where kind = 'antiparasitic' and lower(name) = lower('Поливеркан');
update public.health_products set name_en = 'Prazitel' where kind = 'antiparasitic' and lower(name) = lower('Празител');
update public.health_products set name_en = 'Prazitel Plus' where kind = 'antiparasitic' and lower(name) = lower('Празител Плюс');
update public.health_products set name_en = 'Prazitel tablets' where kind = 'antiparasitic' and lower(name) = lower('Празител таблетки');
update public.health_products set name_en = 'Prazicid' where kind = 'antiparasitic' and lower(name) = lower('Празицид');
update public.health_products set name_en = 'Prazicid tablets' where kind = 'antiparasitic' and lower(name) = lower('Празицид таблетки');
update public.health_products set name_en = 'Prazicid complex' where kind = 'antiparasitic' and lower(name) = lower('Празицид-комплекс');
update public.health_products set name_en = 'Pratel' where kind = 'antiparasitic' and lower(name) = lower('Прател');
update public.health_products set name_en = 'Profender' where kind = 'antiparasitic' and lower(name) = lower('Профендер');
update public.health_products set name_en = 'Rabektra' where kind = 'antiparasitic' and lower(name) = lower('Рабектра');
update public.health_products set name_en = 'Rolf Club 3D' where kind = 'antiparasitic' and lower(name) = lower('Рольф Клуб 3D');
update public.health_products set name_en = 'Rolf Club 3D cat drops' where kind = 'antiparasitic' and lower(name) = lower('Рольф Клуб 3D капли для кошек');
update public.health_products set name_en = 'Rolf Club 3D collar' where kind = 'antiparasitic' and lower(name) = lower('Рольф Клуб 3D ошейник');
update public.health_products set name_en = 'Rolf Club 3D spray' where kind = 'antiparasitic' and lower(name) = lower('Рольф Клуб 3D спрей');
update public.health_products set name_en = 'Selafort' where kind = 'antiparasitic' and lower(name) = lower('Селафорт');
update public.health_products set name_en = 'Simparica' where kind = 'antiparasitic' and lower(name) = lower('Симпарика');
update public.health_products set name_en = 'Simparica Trio' where kind = 'antiparasitic' and lower(name) = lower('Симпарика Трио');
update public.health_products set name_en = 'Scalibor' where kind = 'antiparasitic' and lower(name) = lower('Скалибор');
update public.health_products set name_en = 'Stronghold' where kind = 'antiparasitic' and lower(name) = lower('Стронгхолд');
update public.health_products set name_en = 'Supramil' where kind = 'antiparasitic' and lower(name) = lower('Супрамил');
update public.health_products set name_en = 'Tiksfli' where kind = 'antiparasitic' and lower(name) = lower('Тиксфли');
update public.health_products set name_en = 'Febtal' where kind = 'antiparasitic' and lower(name) = lower('Фебтал');
update public.health_products set name_en = 'Febtal Combo' where kind = 'antiparasitic' and lower(name) = lower('Фебтал Комбо');
update public.health_products set name_en = 'Fenpraz' where kind = 'antiparasitic' and lower(name) = lower('Фенпраз');
update public.health_products set name_en = 'Fenpraz Forte' where kind = 'antiparasitic' and lower(name) = lower('Фенпраз Форте');
update public.health_products set name_en = 'Fiprex 75 spot-on' where kind = 'antiparasitic' and lower(name) = lower('Фипрекс 75 спот-он');
update public.health_products set name_en = 'Fiprex spray forte' where kind = 'antiparasitic' and lower(name) = lower('Фипрекс спрей форте');
update public.health_products set name_en = 'Fypryst Combo' where kind = 'antiparasitic' and lower(name) = lower('Фиприст Комбо');
update public.health_products set name_en = 'Fypryst Spot On' where kind = 'antiparasitic' and lower(name) = lower('Фиприст Спот Он');
update public.health_products set name_en = 'Fypryst Spray' where kind = 'antiparasitic' and lower(name) = lower('Фиприст спрей');
update public.health_products set name_en = 'Fluvecto' where kind = 'antiparasitic' and lower(name) = lower('Флувекто');
update public.health_products set name_en = 'Foresto' where kind = 'antiparasitic' and lower(name) = lower('Форесто');
update public.health_products set name_en = 'Frontline Combo' where kind = 'antiparasitic' and lower(name) = lower('Фронтлайн Комбо');
update public.health_products set name_en = 'Frontline NexGard' where kind = 'antiparasitic' and lower(name) = lower('Фронтлайн НексгарД');
update public.health_products set name_en = 'Frontline Spot On' where kind = 'antiparasitic' and lower(name) = lower('Фронтлайн Спот Он');
update public.health_products set name_en = 'Frontline Spray' where kind = 'antiparasitic' and lower(name) = lower('Фронтлайн Спрей');
update public.health_products set name_en = 'Frontline Tri-Act' where kind = 'antiparasitic' and lower(name) = lower('Фронтлайн Три-Акт');
update public.health_products set name_en = 'Cestal Cat' where kind = 'antiparasitic' and lower(name) = lower('Цестал Кэт');
update public.health_products set name_en = 'Cestal Plus' where kind = 'antiparasitic' and lower(name) = lower('Цестал Плюс');
update public.health_products set name_en = 'Chistotel Glistogon' where kind = 'antiparasitic' and lower(name) = lower('Чистотел Глистогон');
update public.health_products set name_en = 'Chistotel Maximum drops' where kind = 'antiparasitic' and lower(name) = lower('Чистотел Максимум капли');
update public.health_products set name_en = 'Chistotel Maximum collar' where kind = 'antiparasitic' and lower(name) = lower('Чистотел Максимум ошейник');
update public.health_products set name_en = 'Chistotel Maximum spray' where kind = 'antiparasitic' and lower(name) = lower('Чистотел Максимум спрей');
update public.health_products set name_en = 'Ektogardika' where kind = 'antiparasitic' and lower(name) = lower('Эктогардика');
update public.health_products set name_en = 'Effitix' where kind = 'antiparasitic' and lower(name) = lower('Эффитикс');

commit;
