// Types for `import x from './file.png'`. `next-env.d.ts` brings the same
// reference, but it is generated by `next dev`/`next build` and not committed,
// so a clean checkout (CI's typecheck) would not know image modules without it.
/// <reference types="next/image-types/global" />
